* My custom config for Doom Emacs Based from h0cheung's

See [[https://github.com/hlissner/doom-emacs]] for information about Doom Emacs.

This file is an introduction for my config.

** Optimized features

    * fastest LSP (lsp-bridge)

    * C/C++, Python

    * GitHub Copilot

    * systemd units, rpm spec, Arch Linux pkgbuild

    * build and run single files (mainly for competitive programming)

    * rime for butter Chinese input

    * ui tweaks and small tools

    * Emacs Application Framework (EAF)

    * Netease Cloud Music

    * matrix chat

** Recommanded enviromment

*** ArchLinux

Tested with emacs 31.0.50 (master branch).

Doom Emacs supports 29+ now. 31+ is not supported but in fact works well.

Now EAF just support compile emacs with "-with-x-toolkit=gtk3" flags.

EAF does not support PGTK.

If you install emacs from your package manager (without Gentoo Portage),
then lsp-bridge and blink-search won't show icons.

It's recommanded to using "--with-native-compilation=aot" and you will get
a lot of optimize in the speed.

I just support tree-sitter but you can remove the cc-extra in init.el.
